{% set version = "2.2.3" %}
{% set sha256 = "458f80ffcac0ddfba7d3fb2986b6ec271123d4193478a4e807764134e5a6261d" %}

package:
  name: libgd
  version: {{ version }}

source:
  fn: libgd-{{ version }}.tar.gz
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - pkg-config
    - automake
    - gettext
    - zlib 1.2.*
    - freetype 2.6.*
    - jpeg 9*
    - libpng >=1.6.23,<1.7
    - libtiff 4.0.*
    - fontconfig 2.11.*
    - libiconv
    - expat
  run:
    - zlib 1.2.*
    - freetype 2.6.*
    - jpeg 9*
    - libpng >=1.6.23,<1.7
    - libtiff 4.0.*
    - fontconfig 2.11.*
    - libiconv
    - expat

test:
  commands:
    - test -f $PREFIX/lib/libgd.a      # [linux]
    - test -f $PREFIX/lib/libgd.dylib  # [osx]
    - test -f $PREFIX/lib/libgd.la
about:
    home: http://libgd.github.io/
    summary: library for the dynamic creation of images
    license: GD license
    license_family: Other
    license_file: COPYING

extra:
    recipe-maintainers:
      - croth1
      - ChrisBarker-NOAA
