{% set version = "2.2.5" %}

package:
  name: libgd
  version: {{ version }}

source:
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: a66111c9b4a04e818e9e2a37d7ae8d4aae0939a100a36b0ffb52c706a09074b5
  patches:
    # see: https://github.com/libgd/libgd/issues/367
    - patches/linux-fontconfig-basic.patch

build:
  skip: True  # [win]
  number: 4
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libgd
    - {{ pin_subpackage('libgd', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - libtool
    - gettext
    - pkg-config
    - make
  host:
    - expat
    - fontconfig
    - freetype
    - icu
    - jpeg
    - libiconv  # [osx]
    - libpng
    - libtiff
    - libwebp
    - zlib
  run:
    - expat
    - fontconfig
    - freetype
    - icu
    - jpeg
    - libiconv  # [osx]
    - libpng
    - libtiff
    - libwebp
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libgd.a  # [linux]
    - test -f $PREFIX/lib/libgd${SHLIB_EXT}  # [not win]

about:
    home: http://libgd.github.io/
    summary: 'Library for the dynamic creation of images'
    license: GD
    license_family: BSD
    license_file: COPYING

extra:
  recipe-maintainers:
    - croth1
    - ChrisBarker-NOAA
    - ocefpaf
