{% set version = "2.2.4" %}
{% set sha256 = "487a650aa614217ed08ab1bd1aa5d282f9d379cfd95c756aed0b43406381be65" %}

package:
  name: libgd
  version: {{ version }}

source:
  fn: libgd-{{ version }}.tar.gz
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      # see: https://github.com/libgd/libgd/issues/367
      - patches/linux-fontconfig-basic.patch
      - patches/55ac28a293.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - pkg-config
    - gettext
    - zlib 1.2.*
    - freetype 2.7|2.7.*
    - jpeg 9*
    - libpng >=1.6.23,<1.7
    - libtiff 4.0.*
    - fontconfig 2.12.*
    - libiconv
    - icu 56.*
    - expat
    - libwebp
    - automake

  run:
    - zlib 1.2.*
    - freetype 2.7|2.7.*
    - jpeg 9*
    - libpng >=1.6.23,<1.7
    - libtiff 4.0.*
    - fontconfig 2.12.*
    - libiconv
    - icu 56.*
    - expat
    - libwebp

test:
  commands:
    - test -f $PREFIX/lib/libgd.a      # [linux]
    - test -f $PREFIX/lib/libgd.dylib  # [osx]
    - test -f $PREFIX/lib/libgd.la
about:
    home: http://libgd.github.io/
    summary: library for the dynamic creation of images
    license: GD
    license_family: BSD
    license_file: COPYING

extra:
    recipe-maintainers:
      - croth1
      - ChrisBarker-NOAA
