appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: K+jaZicxpGkxg28vhvpyO5pSS8tEOePqz6XdzlfXKtlG58pX2aeCdc57yDZT3/o0FsiCd2sKQGBrHyf3l4Tks1tEOfH//3VhWSwO+bEx78IhtgCtynZ3+vIa/JERMTRppFACVVVkeVUSmnxwv9BAnmVDz9TyGfKTvrdr11NMgyhKSNUpke9cEiZGH8piYdHSQErQYxuHp8ziDycLkU8n5m+mcgDzVq4WsEevQGxbijys1y+VEujUM6FfeMnXIlDT8875cd0ZTVq3QxJVOe8Tw//vgi1Z/n5zqpNcns3gFJ9qoKcOnxD+QGFztrLTiyR+PuiNRWrOAy5dWpYz+w0jKayUGSJZBmVWkPukfsivLRA9hyujfFNORYn3qybmZDMZaVnr7NmcOvJ9E9Mv0dg4vKHnHJEYwUwBTtAHweuJ8k1n3u5MvxUiUjXj38SaxDs0KMMoTgFZiDSVscax7PRgWHpAIa7W+sTosSeNmKUJ0DsuyEdpDSBKRLYteVRRySjLJk16JptytMab9i8PCt7+r0s+BoYF9gvowZUslJ+BeaNZSQG3taRZ9BQT+B7QwH3Y4543WWok0vgh/NTXt+sfT9DDcuTFdfaUVe3+uM0S9QGa35FSKxzMFKNerqXHEewFP5/sAaj6GfMTQwRLVANj82V+c6GoWN+U7wMpbaLhvMs=}
